const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),base='http://localhost:4179';
const initial={records:{
 'admins/admin-one':{active:true,role:'institute_admin',instituteId:'alpha',name:'Institute Owner'},
 'institutes/alpha':{status:'active',instituteName:'Alpha Institute',instituteCode:'ALPHA',examMode:'NORMAL',features:{customLoginFields:true},security:{fullscreen:false},studentFields:[{name:'name',label:'Full Name',type:'text',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'roll',label:'Roll Number',type:'text',required:true}],branding:{},loginTemplateId:'login-classic-01'},
 'institutes/alpha/settings/exam_config':{activeCenterId:'center',activeCenterCode:'CENTER',instituteName:'Alpha Institute',location:'Test City',maxTabSwitches:5,multiExamConfig:[{id:'ssc_gd',name:'SSC GD',active:true,durationMinutes:30,securityPenalty:1,subjects:[{name:'Maths',count:2,order:'sequential'}]}]},
 'institutes/alpha/exams/ssc_gd':{name:'SSC GD',active:true,durationMinutes:30,subjects:[{name:'Maths',count:2,order:'sequential',source:'math.html'}]},
 'institutes/alpha/exams/railway_group_d':{name:'RRB',active:true,durationMinutes:45,subjects:[{name:'All Questions',count:2,order:'random',source:'railway.html'}]},
 'institutes/alpha/question_bank/q1':{examId:'ssc_gd',subject:'Maths',q:'1+1?',options:['2','3','4','5'],a:'2'},
 'institutes/alpha/question_bank/q2':{examId:'ssc_gd',subject:'Maths',q:'2+2?',options:['4','3','2','5'],a:'4'},
 'institutes/alpha/question_bank/q3':{examId:'ssc_gd',subject:'Maths',q:'3+3?',options:['6','3','4','5'],a:'6'},
 'institutes/alpha/results/low':{name:'Low Score',score:'10/80',examId:'ssc_gd'},
 'institutes/alpha/results/high':{name:'High Score',score:'70/80',examId:'ssc_gd'},
 'institutes/alpha/exam_sessions/live':{name:'Live Student',email:'live@gmail.com',examId:'ssc_gd',status:'in_progress',copiesAttempted:3,penaltiesApplied:2,tabSwitches:1}
},users:{'[DEFAULT]':{uid:'student-one',isAnonymous:true}},watchers:[],writes:[]};
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let count=0;
 const context=await browser.newContext();await context.addInitScript(seed=>{const saved=sessionStorage.getItem('mock-state');window.__firebaseMock=saved?JSON.parse(saved):structuredClone(seed);window.__firebaseMock.watchers=[];window.addEventListener('pagehide',()=>sessionStorage.setItem('mock-state',JSON.stringify({...window.__firebaseMock,watchers:[],authListener:undefined})))},initial);
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'firebase-mock.js'),'utf8')});if(url.origin===base){const file=path.join(root,decodeURIComponent(url.pathname));if(fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({contentType:file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':'text/plain',body:fs.readFileSync(file)});return route.fulfill({status:404,body:'missing'})}return route.abort()});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
 const pass=name=>{count++;console.log('PASS '+name)};
 await page.goto(base+'/institute-admin.html');await page.waitForTimeout(100);assert.equal(await page.locator('#loginError').isVisible(),false);assert.equal(await page.evaluate(()=>window.__firebaseMock.users['[DEFAULT]'].uid),'student-one');pass('Anonymous student session is not checked or signed out by admin portal');
 await page.locator('#email').fill('admin@test.com');await page.locator('#password').fill('test-password');await page.locator('#loginForm button').click();await page.locator('#app').waitFor({state:'visible'});pass('Named admin login loads assigned institute');
 await page.locator('#examSelect').selectOption('ssc_gd');await page.locator('#duration').fill('35');await page.locator('#examSelect').selectOption('railway_group_d');await page.locator('#duration').fill('47');await page.locator('#examSelect').selectOption('ssc_gd');assert.equal(await page.locator('#duration').inputValue(),'35');await page.locator('#saveExams').click();assert.equal(await page.evaluate(()=>window.__firebaseMock.records['institutes/alpha/exams/railway_group_d'].durationMinutes),47);pass('Independent exam edits survive dropdown switches and save');
 const names=await page.locator('#resultRows tr').allTextContents();assert(names[0].includes('High Score'));assert(names[1].includes('Low Score'));pass('Legacy score text ranks numerically');
 const row=await page.locator('#securityRows tr').first().innerText();assert(row.includes('3'));assert(row.includes('2'));pass('Security counts read student field names');
 await page.goto(base+'/student-gateway.html');await page.locator('#code').fill('ALPHA');await page.locator('#code-form button').click();await page.locator('#profile-step').waitFor({state:'visible'});assert.equal(await page.locator('#candidate-roll').count(),1);assert.equal(await page.locator('body').getAttribute('data-login-template'),'login-classic-01');pass('Server join, custom required field and login template');
 await page.locator('#candidate-name').fill('Test Candidate');await page.locator('#candidate-email').fill('candidate@gmail.com');await page.locator('#candidate-roll').fill('17');await page.locator('#exam-category').selectOption('ssc_gd');
 const crypto=require('crypto'),hash=crypto.createHash('sha256').update('CENTER').digest('hex');await page.evaluate(hash=>{window.__firebaseMock.records['institutes/alpha/centers/'+hash]={active:true,instituteName:'Alpha Institute',location:'Test City'}},hash);
 await page.locator('#profile-form .primary').click();await page.waitForURL('**/index.html?gateway=1');await page.locator('#slide-2.active').waitFor({timeout:10000});assert((await page.locator('#instruction-duration').innerText()).includes('35'));pass('Gateway handoff reaches instructions with tenant duration');
 await page.locator('#start-exam-btn').click();await page.locator('#slide-3.active').waitFor({timeout:10000});assert.equal(await page.locator('#question-palette button').count(),2);assert.equal(await page.locator('body').evaluate(n=>n.classList.contains('normal-exam')),true);pass('Tenant question count and NORMAL mode apply');
 const stored=await page.evaluate(()=>Object.keys(window.__firebaseMock.records).filter(x=>x.includes('/snapshot/')));assert(stored.length>0);pass('Question snapshot saved before exam');
 await page.reload();await page.locator('#slide-2.active').waitFor();await page.locator('#start-exam-btn').click();await page.locator('#slide-3.active').waitFor();assert.equal(await page.locator('#question-palette button').count(),2);pass('Reload resumes original saved question set');
 await page.locator('.exam-option').first().click();await page.locator('.submit-exam-btn').click();await page.locator('#exam-modal-confirm').click();await page.locator('#slide-4.active').waitFor();await page.locator('#stars-container i').last().click();await page.locator('#submit-all-btn').click();await page.locator('#success-modal.show').waitFor();assert.equal(await page.evaluate(()=>Object.entries(window.__firebaseMock.records).filter(([k,v])=>k.startsWith('institutes/alpha/results/')&&v.completed===true).length),1);pass('Student answers, submits and saves a completed institute result');
 assert.deepEqual(errors,[]);pass('No browser JavaScript exceptions');console.log(`${count} browser checks passed (mock Firebase, not production).`);await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
