const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');let passed=0;
async function test(name,fn){await fn();console.log('PASS '+name);passed++}
const index=read('index.html'),admin=read('institute-admin.html');
const cut=(s,start,end)=>s.slice(s.indexOf(start),s.indexOf(end,s.indexOf(start)));
const scoring=require('../functions/scoring');
// In-memory Admin SDK tests execute the actual callable handlers. No production writes.
function backend(seed){const records=new Map(Object.entries(seed)),writes=[],calls={};let sequence=0;const snapshot=ref=>({exists:records.has(ref.path),data:()=>structuredClone(records.get(ref.path))});
const reference=path=>({path,get:async()=>snapshot({path}),set:async(data,options)=>put(path,data,options),collection:name=>collection(path+'/'+name)});
const collection=path=>({path,doc:id=>reference(path+'/'+(id||'generated-'+(++sequence))),get:async()=>({docs:[...records.keys()].filter(p=>p.startsWith(path+'/')&&!p.slice(path.length+1).includes('/')).map(p=>({...snapshot({path:p}),id:p.split('/').pop(),ref:reference(p)}))})});
function put(path,data,options){records.set(path,options?.merge?{...records.get(path),...data}:structuredClone(data));writes.push(path)}
const batch=()=>{const ops=[];return{set:(ref,data,options)=>ops.push(()=>put(ref.path,data,options)),delete:ref=>ops.push(()=>records.delete(ref.path)),commit:async()=>ops.forEach(fn=>fn())}};
const db={doc:reference,collection,batch,recursiveDelete:async ref=>{for(const p of records.keys())if(p.startsWith(ref.path+'/'))records.delete(p)},runTransaction:async fn=>{const b=batch(),r=await fn({get:async ref=>ref.doc?ref.get():snapshot(ref),set:b.set,delete:b.delete});await b.commit();return r}};
class HttpsError extends Error{constructor(code,message){super(message);this.code=code}}
const ctx={exports:calls,require:name=>name==='firebase-functions/v2/https'?{onCall:(options,fn)=>fn,HttpsError}:name==='firebase-admin/app'?{initializeApp:()=>{}}:name==='firebase-admin/firestore'?{getFirestore:()=>db,FieldValue:{serverTimestamp:()=>123456}}:name==='./scoring'?scoring:{getAuth:()=>({getUser:async()=>({email:'admin@test.com',providerData:[{providerId:'password'}]})})},console};vm.runInNewContext(read('functions/index.js'),ctx);return{calls,records,writes};}
(async()=>{
 await test('Question replacement implementation is unchanged',()=>{assert.equal(require('crypto').createHash('sha256').update(cut(index,'    function replaceViolatedQuestion(){','    function recordSecurityViolation')).digest('hex'),'6e9abd4df085fa2d3f14891b8c5029b281d2a2030e73aa25627435f704817ea7')});
 await test('Question-upload selection and save fields are unchanged',()=>{for(const mode of ['live','code','word'])assert(admin.includes(`value="${mode}"`));assert(admin.includes("uploadMode:document.querySelector('[name=uploadMode]:checked').value"))});
 await test('Tenant SSC timer honours 30 minutes',()=>{const expression=index.match(/const configuredDuration = ([\s\S]*?);/)[1];assert.equal(vm.runInNewContext(expression,{isRailwayExam:()=>false,selectedExamId:'ssc_gd',selectedExamConfig:{tenant:true,durationMinutes:30},examConfigData:{}}),30)});
 await test('Legacy SSC timer remains 60 minutes',()=>{const expression=index.match(/const configuredDuration = ([\s\S]*?);/)[1];assert.equal(vm.runInNewContext(expression,{isRailwayExam:()=>false,selectedExamId:'ssc_gd',selectedExamConfig:{durationMinutes:30},examConfigData:{}}),60)});
 await test('Score text sorts high-to-low correctly',()=>{const source=cut(admin,'const scoreValue=','function renderResults');const c={results:[{id:'low',score:'10/80'},{id:'high',score:'70/80'}],$:id=>({value:id==='resultSort'?'high':''})};assert.equal(vm.runInNewContext(source+'filteredResults()[0].id',c),'high')});
 await test('Score text sorts low-to-high correctly',()=>{const source=cut(admin,'const scoreValue=','function renderResults');const c={results:[{id:'high',score:'70/80'},{id:'low',score:'10/80'}],$:id=>({value:id==='resultSort'?'low':''})};assert.equal(vm.runInNewContext(source+'filteredResults()[0].id',c),'low')});
 await test('Question bank honours configured count and sequential order',async()=>{const source=cut(index,'    async function loadConfiguredExamQuestions(exam,','      // Railway Group D')+'}';const c={currentInstitute:{id:'alpha'},db:{},getDocs:async()=>({docs:[0,1,2,3,4].map(i=>({id:String(i),data:()=>({subject:'Maths'})}))}),query:()=>'',collection:()=>'',where:()=>'',getSubjectEntries:e=>Object.entries(e.subjects),getSubjectCount:c=>c.count,getSubjectOrder:c=>c.order,exam:{id:'math',tenant:true,subjects:{math:{name:'Maths',count:2,order:'sequential'}}}};const rows=await vm.runInNewContext(source+'loadConfiguredExamQuestions(exam)',c);assert.equal(rows.length,2);assert.equal(rows.map(x=>x.id).join(','),'0,1')});
 await test('Snapshot resume returns original questions without bank access',async()=>{const source=cut(index,'    async function loadAttemptSnapshot','    async function saveAttemptSnapshot');const c={currentInstitute:{id:'alpha'},currentSession:{snapshotParts:2},currentAttemptId:'x',db:{},collection:()=>'',getDocs:async()=>({docs:[{data:()=>({order:1,questions:[{id:'original2'}]})},{data:()=>({order:0,questions:[{id:'original1'}]})}]})};const rows=await vm.runInNewContext(source+'loadAttemptSnapshot()',c);assert.equal(rows.map(x=>x.id).join(','),'original1,original2')});
 await test('Incomplete snapshot fails instead of silently dropping questions',async()=>{const source=cut(index,'    async function loadAttemptSnapshot','    async function saveAttemptSnapshot');const c={currentInstitute:{id:'alpha'},currentSession:{snapshotParts:2},currentAttemptId:'x',db:{},collection:()=>'',getDocs:async()=>({docs:[{data:()=>({order:0,questions:[{id:'one'}]})}]})};await assert.rejects(vm.runInNewContext(source+'loadAttemptSnapshot()',c),/incomplete/)});
 await test('Offline scoring uses saved answers and penalties',()=>{const result=scoring.scoreSavedSession({status:'in_progress',grading:[0,1,2],selectedAnswers:{0:0,1:0},penaltiesApplied:.25});assert.equal(result.score,'0.5/3');assert.equal(result.correct,1);assert.equal(result.wrong,1)});
 await test('Not-started attempt cannot be force-scored as zero',()=>assert.throws(()=>scoring.scoreSavedSession({status:'logged_in'}),/not started/));
 await test('Legacy pending result can be finalized',()=>assert.equal(scoring.scoreSavedSession({status:'result_pending_feedback'},{score:'45/80'}).score,'45/80'));
 await test('Missing grading refuses fake 0/0 completion',()=>assert.throws(()=>scoring.scoreSavedSession({status:'in_progress'}),/no saved grading/));
 const id='a'.repeat(64),seed={'admins/admin':{active:true,role:'institute_admin',instituteId:'alpha'},'institutes/alpha':{status:'active'},[`institutes/alpha/exam_sessions/${id}`]:{instituteId:'alpha',ownerUid:'student',name:'Candidate',email:'a@gmail.com',examId:'ssc',status:'in_progress',grading:[0,1],selectedAnswers:{0:0,1:1},penaltiesApplied:0},[`attempt_locks/${id}`]:{instituteId:'alpha',ownerUid:'student'},[`exam_sessions/${id}`]:{instituteId:'alpha',ownerUid:'student'}};
 await test('Force submit writes completed institute result without student browser',async()=>{const b=backend(seed);await b.calls.forceSubmitInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}});assert.equal(b.records.get(`institutes/alpha/results/${id}`).score,'2/2');assert.equal(b.records.get(`institutes/alpha/exam_sessions/${id}`).status,'final_submitted')});
 await test('Repeated force submit does not overwrite completed result',async()=>{const b=backend({...seed,[`institutes/alpha/results/${id}`]:{completed:true,score:'1/2'}});const result=await b.calls.forceSubmitInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}});assert.equal(result.alreadyCompleted,true);assert.equal(b.records.get(`institutes/alpha/results/${id}`).score,'1/2');assert.equal(b.writes.length,0)});
 await test('Another institute admin cannot force submit',async()=>{const b=backend({...seed,'admins/admin':{active:true,role:'institute_admin',instituteId:'beta'}});await assert.rejects(b.calls.forceSubmitInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}}),e=>e.code==='permission-denied');assert.equal(b.writes.length,0)});
 await test('Suspended institute cannot force submit',async()=>{const b=backend({...seed,'institutes/alpha':{status:'suspended'}});await assert.rejects(b.calls.forceSubmitInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}}),e=>e.code==='failed-precondition')});
 await test('Retake clears tenant records, snapshots and global lock/session',async()=>{const b=backend({...seed,[`institutes/alpha/exam_sessions/${id}/snapshot/0000`]:{questions:[]},[`institutes/alpha/results/${id}`]:{instituteId:'alpha'}});await b.calls.resetInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}});assert(!b.records.has(`attempt_locks/${id}`));assert(!b.records.has(`exam_sessions/${id}`));assert(!b.records.has(`institutes/alpha/exam_sessions/${id}/snapshot/0000`));assert(!b.records.has(`institutes/alpha/results/${id}`))});
 await test('Wrong institute cannot clear retake locks',async()=>{const b=backend({...seed,'admins/admin':{active:true,role:'institute_admin',instituteId:'beta'}});await assert.rejects(b.calls.resetInstituteAttempt({auth:{uid:'admin'},data:{instituteId:'alpha',attemptId:id}}),e=>e.code==='permission-denied');assert(b.records.has(`attempt_locks/${id}`))});
 const joinSeed={'institute_codes/alpha':{instituteId:'alpha'},'institutes/alpha':{status:'active'},'institutes/alpha/settings/exam_config':{activeCenterId:'center'},'institutes/alpha/centers/center':{active:true},'institutes/alpha/exams/ssc':{active:true}};
 await test('Valid institute code grants only requested membership',async()=>{const b=backend(joinSeed);const result=await b.calls.joinInstitute({auth:{uid:'student'},data:{code:'ALPHA'}});assert.equal(result.instituteId,'alpha');assert(b.records.has('institutes/alpha/members/student'));assert(!b.records.has('institutes/beta/members/student'))});
 await test('Incomplete onboarding fails before student handoff',async()=>{const b=backend({...joinSeed,'institutes/alpha/settings/exam_config':{}});await assert.rejects(b.calls.joinInstitute({auth:{uid:'student'},data:{code:'ALPHA'}}),/save an active center/);assert(!b.records.has('institutes/alpha/members/student'))});
 await test('Invalid institute code creates no membership',async()=>{const b=backend(joinSeed);await assert.rejects(b.calls.joinInstitute({auth:{uid:'student'},data:{code:'OTHER'}}),/Invalid institute/);assert.equal(b.writes.length,0)});
 console.log(`${passed} regression checks passed. Firebase is mocked; deployed rules are not verified.`);
})().catch(e=>{console.error(e);process.exitCode=1});
